Apply changes to solve the errors
TypeError: Cannot read properties of undefined (reading 'nepal')
    at parseGeographies (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/src_fbb10573._.js:468:71)
    at S (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/node_modules_ad70f122._.js:14897:20)
    at T.useEffect (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/node_modules_ad70f122._.js:14939:34)
    at HomepageMap (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/src_fbb10573._.js:466:231)
    at LoadableComponent (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/node_modules_dcf59619._.js:235:57)
    at Hero (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/src_components_ddd2c129._.js:166:227)
    at HomePage (rsc://React/Server/file:///home/user/studio/.next/server/chunks/ssr/%5Broot%20of%20the%20server%5D__78263028._.js?92:1075:264)