Solve this error below
TypeError: Constructor Map requires 'new'
    at Map (<anonymous>)
    at renderDetailAccordionItem (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/src_a275ded1._.js:765:231)
    at RecommendationsPage (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/src_a275ded1._.js:1133:53)
    at ClientPageRoot (https://6000-firebase-studio-1747061545577.cluster-htdgsbmflbdmov5xrjithceibm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)